version: "3"

services:
  app:
    build:
      context: ./.docker/apache
      args:
        - PHP_VERSION=${PHP_VERSION:-7.4}
    ports:
      - ${APP_PORT:-80}:80
    restart: unless-stopped
    volumes:
      - ${APP_DIR:-./app}:/var/www/html:z
      - ./.docker/apache/app.apache.conf:/etc/apache2/sites-available/000-default.conf
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    links:
      - php
      - mariadb
    depends_on:
      - php
  composer:
    build:
      context: ./.docker/composer
      args:
        - PHP_VERSION=${PHP_VERSION:-7.4}
    volumes:
      - ${APP_DIR:-./app}:/var/www/html
    command: composer install
    depends_on:
      - app
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE:-app}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-t00r}
      - MYSQL_USER=${MARIADB_USER:-app}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD:-t00r}
    volumes:
      - ${MARIADB_DATA_DIR:-./.docker/mysql/data}:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT:-8080}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    links:
      - mariadb
